<?php
return [
    //format: unique identifier => [data]
    '1' => [
        'id'           => 1,
        'title'        => 'Test Article 1',
        'imagefile'    => '',
        'category_id'  => 1,
        'description'  => 'Description of Article 1',
        'content'      => 'Content of Article 1',
        'status'       => 'published',
        'enabled'      => 1,
        'display'      => 1,
        'created_at'   => '2017-07-11 18:49:54',
        'updated_at'   => '2017-07-11 18:49:54',
        'published_at' => '2017-07-11 18:49:54',
    ],
    '2' => [
        'id'           => 2,
        'title'        => 'Test Article 2',
        'imagefile'    => '',
        'category_id'  => 2,
        'description'  => 'Description of Article 2',
        'content'      => 'Content of Article 2',
        'status'       => 'published',
        'enabled'      => 1,
        'display'      => 1,
        'created_at'   => '2017-07-11 18:49:55',
        'updated_at'   => '2017-07-11 18:49:55',
        'published_at' => '2017-07-11 18:49:55',
    ],
    '3' => [
        'id'           => 3,
        'title'        => 'Test Article 3',
        'imagefile'    => '',
        'category_id'  => 3,
        'description'  => 'Description of Article 3',
        'content'      => 'Content of Article 3',
        'status'       => 'published',
        'enabled'      => 1,
        'display'      => 1,
        'created_at'   => '2017-07-11 18:49:56',
        'updated_at'   => '2017-07-11 18:49:56',
        'published_at' => '2017-07-11 18:49:56',
    ],
];
